# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-03 10:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Catagory',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='catagory',
            new_name='category',
        ),
    ]
