# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20160705_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='abstract',
            field=models.TextField(blank=True, max_length=140, null=True, verbose_name='摘要'),
        ),
    ]
